### ISSUE TITLE
filament v3 edit url error

### ISSUE THREAD

**Issue by vinayakdev** [lukeraymonddowning/self-healing-urls#4]
since this tinkers with RouteKey, not able to edit the record on filament when using this package, any way i can circumvent that

**Comment by taliesinpenbardd** [comment]
I encounter the same problem.
With Filament V3 (and Laravel 10), the Filament edit URL for a Post model is `/admin/posts/slug-of-the-post-1/edit` and it results with a 404 error. 
I've been trying to fiddle with `Resource::getRouteKeyName()` and `Resource::getRecordRouteKeyName()` but no luck so far.
Any idea on how we could make this work?
Anyway, thanks for this neat package.

**Comment by taliesinpenbardd** [comment]
Got it to work, using this solution: simple and elegant!
https://github.com/filamentphp/filament/issues/10389#issuecomment-1862970238
